using System.Text;

namespace SLANGCompiler.SlfsPack;

/// <summary>
/// SLFS asset id → SLANG `CONST` 形式 .inc header 生成。 packer の D88 build と
/// 同 sort 順 (= normalized filename ordinal 昇順) で id を割当、 user 入力
/// filename ベースで `FILE_<NAME>` identifier を生成。
///
/// SLANG sample で `#INCLUDE <stem>.assets.inc` で取り込む想定、 numeric ID
/// 直書きの問題 (= sort 順依存 / typo 検出不能) を解消する。
///
/// 責務分離: packer (= SlfsPackerLibrary) は D88 build 専門、 header 生成は
/// 本 class で independent (= dummy main 不要、 static helper)。
/// </summary>
public static class SlfsHeaderBuilder
{
    /// <summary>asset list を sort 後、 SLANG CONST 形式 .inc 文字列を生成。
    /// 空 asset → 空 string。 identifier collision (= 変換後同一) は throw。</summary>
    public static string Build(IEnumerable<SlfsPackerLibrary.AssetEntry> assets)
    {
        if (assets == null) throw new ArgumentNullException(nameof(assets));

        // SortedAssets と同 logic (= normalized filename ordinal 昇順) を inline 化
        // (= packer 構築前でも呼べる static、 BuildHeader が SlfsPackerLibrary 構築に
        //  依存しないため main binary 不要)
        var sorted = assets
            .Select(a => (Asset: a, NormName: SlfsDirEntry.NormalizeFileName(a.Name)))
            .OrderBy(x => x.NormName, Comparer<byte[]>.Create(SlfsDirEntry.CompareNormalizedFileName))
            .Select(x => x.Asset)
            .ToList();

        if (sorted.Count == 0) return "";

        // identifier 化 + collision check
        var entries = new List<(string Identifier, int Id)>();
        var seenIdentifiers = new Dictionary<string, string>(StringComparer.Ordinal);
        for (int id = 0; id < sorted.Count; id++)
        {
            var ident = ToIdentifier(sorted[id].Name);
            if (seenIdentifiers.TryGetValue(ident, out var existing))
                throw new InvalidOperationException(
                    $"asset identifier collision: '{sorted[id].Name}' → '{ident}' " +
                    $"(already used by '{existing}'). Rename one to avoid conflict.");
            seenIdentifiers[ident] = sorted[id].Name;
            entries.Add((ident, id));
        }

        // SLANG CONST 構文: `CONST A = 0, B = 1, ...;`
        // identifier 列の最大幅で揃えて見やすく
        int maxLen = entries.Max(e => e.Identifier.Length);
        var sb = new StringBuilder();
        sb.AppendLine("// SLFS asset id map (auto-generated by slfs-pack、 編集禁止)");
        sb.Append("CONST ");
        for (int i = 0; i < entries.Count; i++)
        {
            if (i > 0) sb.Append("      ");
            sb.Append(entries[i].Identifier.PadRight(maxLen));
            sb.Append(" = ");
            sb.Append(entries[i].Id);
            sb.Append(i < entries.Count - 1 ? ",\n" : ";\n");
        }
        return sb.ToString();
    }

    /// <summary>user 入力 filename を SLANG identifier に変換:
    /// - `ToUpperInvariant()` (= locale 非依存)
    /// - 英数字以外 (= `.` `-` ` ` 等含む全て) を `_` に置換
    /// - prefix `FILE_` 追加
    /// - 例: `GREETING.TXT` → `FILE_GREETING_TXT`、 `MY ASSET-1.BIN` → `FILE_MY_ASSET_1_BIN`
    /// </summary>
    public static string ToIdentifier(string name)
    {
        if (string.IsNullOrEmpty(name)) return "FILE_";
        var upper = name.ToUpperInvariant();
        var sb = new StringBuilder("FILE_", 5 + upper.Length);
        foreach (var ch in upper)
        {
            sb.Append((ch >= 'A' && ch <= 'Z') || (ch >= '0' && ch <= '9') ? ch : '_');
        }
        return sb.ToString();
    }
}
