; Converted from /home/user/SLANG-compiler/lib/libdef/libmsx_grp.yml
; SLANG Runtime Library (new format)

; @name MSXGRPBASE
; @calls MSXGRPSYS,MSXGRPWORK
; @lib MSXLIB
CONSOLE_COLUMNS equ 32
CONSOLE_ROWS equ 24
CALSLT EQU $001C
WRTVRM EQU $004D
SETWRT EQU $0053
FILVRM equ $0056
LDIRVM equ $005C
INIGRP equ $0072
INIMLT equ $0075
CHGCLR equ $0062
INIT32 equ $006F
INITXT EQU $006C
WRTVDP EQU $0047

BDRCLR equ $F3EB
FORCLR equ $F3E9
BAKCLR equ $F3EA

RG0SAV EQU $F3DF
RG1SAV EQU $F3E0
RG2SAV EQU $F3E1
RG3SAV EQU $F3E2
RG4SAV EQU $F3E3
RG5SAV EQU $F3E4
RG6SAV EQU $F3E5
RG7SAV EQU $F3E6

VDP_DATA EQU $98
VDP_DATAIN EQU $98
VDP_CMD EQU $99
VDP_STATUS EQU $99


; @name MSX_CALLBIOS
; @lib MSXLIB
; @extlib MSX.ASM:MSXCALLBIOS

; @name MSX_SCREEN
; @lib MSXLIB
; @extlib MSX.ASM:MSX_SCREEN

; @name MSXGRPSYS
; @lib MSXLIB
; @extlib MSX.ASM:MSXGRPBASE

; @name MSX_SET_COLOR
; @calls MSXGRPBASE,MSXGRPWORK,MSXGRPSYS
; @lib MSXLIB
; @extlib MSX.ASM:MSXSETCOLOR

; @name MSX_VWRITE
; @calls MSXGRPBASE,MSXGRPWORK,MSXGRPSYS
; @lib MSXLIB
; @extlib MSX.ASM:MSX_VWRITE

; @name MSX_VWRITE_DIRECT
; @calls MSXGRPBASE,MSXGRPWORK,MSXGRPSYS
; @lib MSXLIB
; @extlib MSX.ASM:MSX_VWRITE_DIRECT

; @name MSX_VFILL
; @calls MSXGRPBASE,MSXGRPWORK,MSXGRPSYS
; @lib MSXLIB
; @extlib MSX.ASM:MSX_VFILL

; @name GET_VDP_REG
; @calls MSXGRPBASE,MSXGRPWORK,MSXGRPSYS
; @lib MSXLIB
; @extlib MSX.ASM:GET_VDP_REG

; @name SET_VDP_REG
; @calls MSXGRPBASE,MSXGRPWORK,MSXGRPSYS
; @lib MSXLIB
; @extlib MSX.ASM:SET_VDP_REG

; @name SET_SPRITE_16HFLIP
; @calls MSXGRPBASE,MSXGRPWORK,MSXGRPSYS
; @lib MSXLIB
; @extlib MSX.ASM:SET_SPRITE_16HFLIP

; @name MSXGRPWORK
; @lib MSXLIB
;


; @name MSXCALLS
CHPUT   EQU $00A2
EXPTBL  EQU $FCC1
ENASLT  EQU $0024
INIT32  EQU $006F
RSLREG  EQU $0138
CHGMOD  EQU $005F
LINL40  EQU $F3AE
POSIT   EQU $00C6
GTSTCK  EQU $00D5


; @name STICK2
; @calls MSXCALLS
LD A,L
LD IX,GTSTCK
CALL MSXLIB.msxbios
; CALL GTSTCK
LD HL,STICK_TBL
LD E,A
LD D,0
ADD HL,DE
LD A,(HL)
LD L,A
LD H,0
RET
STICK_TBL:
DB 00H
DB 01H
DB 03H
DB 02H
DB 06H
DB 04H
DB 0CH
DB 08H
DB 09H


