#!/usr/bin/env python3
"""
UTF-8 文字列を CHARMAP (JSON) に従って 1..255 のバイト列にエンコードし、
SLANG の ARRAY BYTE 定義を生成する。

CHARMAP は AILZ80ASM の CHARMAP JSON と同じ形式:
    { "あ": [1], "い": [2], "ｷ": [135, 136], ... }
値 (配列) の各要素は 1..255 の整数 (0 は UI_PUTS 終端予約のため禁止)。

Usage:
    # CLI 単発
    python3 tools/charmap-encode.py \\
        --charmap assets/ui/uicharset1.json \\
        --name MSG_HELLO \\
        "あいうえお"

    # JSON 一括
    python3 tools/charmap-encode.py \\
        --charmap assets/ui/uicharset1.json \\
        --input examples/ui/strings.json \\
        --out examples/ui/strings.sl

Python 標準ライブラリのみ使用。
"""

import argparse
import json
import sys


def load_charmap(path):
    """CHARMAP JSON を読み、{ char: [byte, ...] } を返す。
    値の範囲 (1..255) をその場で検証する。"""
    with open(path, "r", encoding="utf-8") as f:
        raw = json.load(f)

    if not isinstance(raw, dict):
        raise ValueError(f"{path}: top-level must be a JSON object")

    cmap = {}
    for key, val in raw.items():
        if not isinstance(val, list):
            raise ValueError(
                f"{path}: value for key {key!r} is not a list: {val!r}"
            )
        for elem in val:
            if not isinstance(elem, int):
                raise ValueError(
                    f"{path}: non-integer byte in mapping for {key!r}: {elem!r}"
                )
            if not (1 <= elem <= 255):
                raise ValueError(
                    f"{path}: byte out of range (1..255) in mapping for {key!r}: {elem}"
                )
        cmap[key] = list(val)
    return cmap


def encode_string(s, cmap, context):
    """UTF-8 文字列を CHARMAP で引いてバイト列に変換。
    未定義文字はエラー (context は診断メッセージ用)。"""
    out = []
    for i, ch in enumerate(s):
        if ch not in cmap:
            raise ValueError(
                f"{context}: char {ch!r} (U+{ord(ch):04X}) at index {i} not in charmap"
            )
        out.extend(cmap[ch])
    return out


def format_array(name, bytes_):
    """ARRAY BYTE NAME[] = { 1, 2, 3, 0 }; を組み立てる。zero 終端付き。"""
    items = ", ".join(str(b) for b in bytes_)
    if items:
        return f"ARRAY BYTE {name}[] = {{ {items}, 0 }};"
    else:
        return f"ARRAY BYTE {name}[] = {{ 0 }};"


def main():
    ap = argparse.ArgumentParser(
        description=__doc__.split("\n\n")[0],
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("--charmap", required=True, help="CHARMAP JSON path")
    ap.add_argument("--name", help="SLANG array name (CLI mode)")
    ap.add_argument("--input", help="input JSON ({ name: string, ... }) for batch mode")
    ap.add_argument("--out", help="output .sl file path (batch mode, default stdout)")
    ap.add_argument("text", nargs="?", help="text to encode (CLI mode)")
    args = ap.parse_args()

    cmap = load_charmap(args.charmap)

    if args.input:
        with open(args.input, "r", encoding="utf-8") as f:
            entries = json.load(f)
        if not isinstance(entries, dict):
            sys.exit(f"{args.input}: expected JSON object at top level")

        lines = []
        lines.append(f"/// Generated by tools/charmap-encode.py")
        lines.append(f"/// charmap: {args.charmap}")
        lines.append(f"/// input:   {args.input}")
        lines.append("")
        for name, text in entries.items():
            if not isinstance(text, str):
                sys.exit(f"{args.input}: value for {name!r} is not a string")
            try:
                bytes_ = encode_string(text, cmap, context=name)
            except ValueError as e:
                sys.exit(f"error: {e}")
            lines.append(format_array(name, bytes_))

        output = "\n".join(lines) + "\n"
        if args.out:
            with open(args.out, "w", encoding="utf-8") as f:
                f.write(output)
            print(f"wrote {args.out}", file=sys.stderr)
        else:
            sys.stdout.write(output)
    else:
        if not args.name or args.text is None:
            sys.exit("CLI mode requires --name and a text argument")
        try:
            bytes_ = encode_string(args.text, cmap, context=args.name)
        except ValueError as e:
            sys.exit(f"error: {e}")
        print(format_array(args.name, bytes_))


if __name__ == "__main__":
    main()
