/// Generated by tools/charmap-encode.py
/// charmap: assets/ui/uicharset1.json
/// input:   examples/ui/strings.json

ARRAY BYTE MSG_TITLE[] = { 85, 73, 76, 73, 66, 32, 84, 69, 83, 84, 0 };
ARRAY BYTE MSG_HELLO[] = { 72, 69, 76, 76, 79, 32, 85, 73, 0 };
ARRAY BYTE MSG_SCORE[] = { 83, 67, 79, 82, 69, 0 };
ARRAY BYTE MSG_POWER[] = { 80, 79, 87, 69, 82, 0 };
ARRAY BYTE MSG_PRESS[] = { 80, 82, 69, 83, 83, 32, 65, 78, 89, 32, 75, 69, 89, 0 };
