//
//  This CSharp output file generated by Gardens Point LEX
//  Gardens Point LEX (GPLEX) is Copyright (c) John Gough, QUT 2006-2014.
//  Output produced by GPLEX is the property of the user.
//  See accompanying file GPLEXcopyright.rtf.
//
//  GPLEX Version:  1.2.2
//  DateTime: 12/29/2025 9:25:16PM
//  GPLEX input file <SLANG/SLANG.Language.analyzer.lex - 12/29/2025 2:28:06PM>
//  GPLEX frame file <embedded resource>
//
//  Option settings: unicode, verbose, parser, stack, minimize
//  Option settings: classes, compressMap, compressNext, persistBuffer, noEmbedBuffers
//  Fallback code page: utf-8
//

//
// Revised backup code
// Version 1.2.1 of 24-June-2013
//
//
#define BACKUP
#define LEFTANCHORS
#define STACK
#define PERSIST

using System;
using System.IO;
using System.Text;
using System.Globalization;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Diagnostics.CodeAnalysis;

using QUT.GplexBuffers;

namespace SLANGCompiler.SLANG
{   
    /// <summary>
    /// Summary Canonical example of GPLEX automaton
    /// </summary>
    
#if STANDALONE
    //
    // These are the dummy declarations for stand-alone GPLEX applications
    // normally these declarations would come from the parser.
    // If you declare /noparser, or %option noparser then you get this.
    //

     internal enum Token
    { 
      EOF = 0, maxParseToken = int.MaxValue 
      // must have at least these two, values are almost arbitrary
    }

     internal abstract class ScanBase
    {
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yylex")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yylex")]
        public abstract int yylex();

        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yywrap")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yywrap")]
        protected virtual bool yywrap() { return true; }

#if BABEL
        protected abstract int CurrentSc { get; set; }
        // EolState is the 32-bit of state data persisted at 
        // the end of each line for Visual Studio colorization.  
        // The default is to return CurrentSc.  You must override
        // this if you want more complicated behavior.
        public virtual int EolState { 
            get { return CurrentSc; }
            set { CurrentSc = value; } 
        }
    }
    
     internal interface IColorScan
    {
        void SetSource(string source, int offset);
        int GetNext(ref int state, out int start, out int end);
#endif // BABEL
    }

#endif // STANDALONE
    
    // If the compiler can't find the scanner base class maybe you
    // need to run GPPG with the /gplex option, or GPLEX with /noparser
#if BABEL
     internal sealed partial class SLANGScanner : ScanBase, IColorScan
    {
        private ScanBuff buffer;
        int currentScOrd;  // start condition ordinal
        
        protected override int CurrentSc 
        {
             // The current start state is a property
             // to try to avoid the user error of setting
             // scState but forgetting to update the FSA
             // start state "currentStart"
             //
             get { return currentScOrd; }  // i.e. return YY_START;
             set { currentScOrd = value;   // i.e. BEGIN(value);
                   currentStart = startState[value]; }
        }
#else  // BABEL
     internal sealed partial class SLANGScanner : ScanBase
    {
        private ScanBuff buffer;
        int currentScOrd;  // start condition ordinal
#endif // BABEL
        
        /// <summary>
        /// The input buffer for this scanner.
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ScanBuff Buffer { get { return buffer; } }
        
        private static int GetMaxParseToken() {
     System.Reflection.FieldInfo f = typeof(Token).GetField("maxParseToken");
            return (f == null ? int.MaxValue : (int)f.GetValue(null));
        }
        
        static int parserMax = GetMaxParseToken();
        
        enum Result {accept, noMatch, contextFound};

        const int maxAccept = 131;
        const int initial = 132;
        const int eofNum = 0;
        const int goStart = -1;
        const int INITIAL = 0;
        const int COMMENT = 1;
        const int LINECOMMENT = 2;
        const int STRING = 3;
        const int CHARCONST = 4;
        const int INCL = 5;
        const int PREIFSKIP = 6;
        const int SKIPEOL = 7;
        const int ASM = 8;

#region user code
StringBuilder lexStrBuffer = null;
    int prevTokEPos = 0;
    bool nextBraceIsArray = false;

    private class LocationInfo
    {
        private string fileName;
        public string FileName => fileName;

        private QUT.Gppg.LexLocation location;
        public QUT.Gppg.LexLocation Location => location;

        public LocationInfo(string fileName, QUT.Gppg.LexLocation location)
        {
            this.fileName = fileName;
            this.location = location;
        }
    }

    Stack<LocationInfo> locationStack = new Stack<LocationInfo>();
    Stack<bool> skipStack = new Stack<bool>();
    int preIfSkipCount = 0;
    public bool moduleMode = false;
    public int moduleCount = 0;
    
    private class ContextInfo
    {
        public bool useLocation;
        public BufferContext context;
        public ContextInfo(BufferContext context, bool useLocation)
        {
            this.context = context;
            this.useLocation = useLocation;
        }
    }

    Stack<ContextInfo> buffStack = new Stack<ContextInfo>();
    string Indent() { return new string(' ', buffStack.Count * 4); }
#endregion user code

        int state;
        int currentStart = startState[0];
        int code;      // last code read
        int cCol;      // column number of code
        int lNum;      // current line number
        //
        // The following instance variables are used, among other
        // things, for constructing the yylloc location objects.
        //
        int tokPos;        // buffer position at start of token
        int tokCol;        // zero-based column number at start of token
        int tokLin;        // line number at start of token
        int tokEPos;       // buffer position at end of token
        int tokECol;       // column number at end of token
        int tokELin;       // line number at end of token
        string tokTxt;     // lazily constructed text of token
#if STACK          
        private Stack<int> scStack = new Stack<int>();
#endif // STACK

#region ScannerTables
    struct Table {
        public int min; public int rng; public int dflt;
        public short[] nxt;
        public Table(int m, int x, int d, short[] n) {
            min = m; rng = x; dflt = d; nxt = n;
        }
    };

    static int[] startState = new int[] {132, 181, 182, 183, 196, 197, 
        198, 205, 206, 0};

   static int[] anchorState = new int[] {133, 181, 182, 183, 196, 197, 
        198, 205, 206, 0};

#region TwoLevelCharacterMap
    //
    // There are 76 equivalence classes
    // There are 256 character sequence regions
    // There are 5 tables, 1280 entries
    //
    static sbyte[] mLo0 = new sbyte[256] {
/*     '\0' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 46, 65, 68, 68, 64, 68, 68, 
/*   '\x10' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/*   '\x20' */ 46, 22, 69, 10, 3, 18, 16, 67, 30, 31, 25, 23, 40, 24, 2, 26, 
/*      '0' */ 8, 6, 58, 70, 59, 70, 70, 70, 1, 1, 41, 43, 20, 19, 21, 42, 
/*      '@' */ 44, 71, 7, 11, 29, 52, 15, 61, 12, 14, 45, 13, 63, 27, 73, 28, 
/*      'P' */ 55, 45, 72, 74, 75, 66, 45, 45, 57, 45, 45, 32, 0, 33, 44, 44, 
/*      '`' */ 68, 4, 7, 53, 51, 52, 47, 61, 5, 54, 45, 45, 63, 50, 56, 48, 
/*      'p' */ 55, 45, 49, 60, 62, 66, 45, 45, 9, 45, 45, 34, 17, 35, 68, 68, 
/*   '\x80' */ 45, 68, 68, 68, 68, 45, 68, 45, 68, 68, 68, 68, 68, 68, 68, 68, 
/*   '\x90' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/*   '\xA0' */ 68, 68, 38, 39, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/*   '\xB0' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 45, 68, 37, 68, 68, 
/*   '\xC0' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/*   '\xD0' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/*   '\xE0' */ 68, 68, 68, 45, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 36, 
/*   '\xF0' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68 };
    static sbyte[] mLo1 = new sbyte[256] {
/* '\u0100' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/* '\u0110' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/* '\u0120' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/* '\u0130' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/* '\u0140' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/* '\u0150' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/* '\u0160' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/* '\u0170' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/* '\u0180' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/* '\u0190' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/* '\u01A0' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/* '\u01B0' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/* '\u01C0' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/* '\u01D0' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/* '\u01E0' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/* '\u01F0' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68 };
    static sbyte[] mLo48 = new sbyte[256] {
/* '\u3000' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/* '\u3010' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/* '\u3020' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/* '\u3030' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/* '\u3040' */ 68, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
/* '\u3050' */ 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
/* '\u3060' */ 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
/* '\u3070' */ 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
/* '\u3080' */ 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
/* '\u3090' */ 45, 45, 45, 45, 45, 45, 45, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/* '\u30A0' */ 68, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
/* '\u30B0' */ 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
/* '\u30C0' */ 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
/* '\u30D0' */ 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
/* '\u30E0' */ 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
/* '\u30F0' */ 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 68, 68, 68, 68, 68 };
    static sbyte[] mLo52 = new sbyte[256] {
/* '\u3400' */ 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
/* '\u3410' */ 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
/* '\u3420' */ 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
/* '\u3430' */ 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
/* '\u3440' */ 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
/* '\u3450' */ 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
/* '\u3460' */ 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
/* '\u3470' */ 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
/* '\u3480' */ 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
/* '\u3490' */ 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
/* '\u34A0' */ 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
/* '\u34B0' */ 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
/* '\u34C0' */ 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
/* '\u34D0' */ 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
/* '\u34E0' */ 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
/* '\u34F0' */ 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45 };
    static sbyte[] mLo216 = new sbyte[256] {
/* '\uD800' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/* '\uD810' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/* '\uD820' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/* '\uD830' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/* '\uD840' */ 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
/* '\uD850' */ 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
/* '\uD860' */ 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
/* '\uD870' */ 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
/* '\uD880' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/* '\uD890' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/* '\uD8A0' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/* '\uD8B0' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/* '\uD8C0' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/* '\uD8D0' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/* '\uD8E0' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 
/* '\uD8F0' */ 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68 };

    static sbyte[][] map = new sbyte[256][] {
/* '\u00xx' */ mLo0, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, 
/* '\u10xx' */ mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, 
/* '\u20xx' */ mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, 
/* '\u30xx' */ mLo48, mLo1, mLo1, mLo1, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, 
/* '\u40xx' */ mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, 
/* '\u50xx' */ mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, 
/* '\u60xx' */ mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, 
/* '\u70xx' */ mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, 
/* '\u80xx' */ mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, 
/* '\u90xx' */ mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, mLo52, 
/* '\uA0xx' */ mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, 
/* '\uB0xx' */ mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, 
/* '\uC0xx' */ mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, 
/* '\uD0xx' */ mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo216, mLo1, mLo1, mLo1, mLo52, mLo52, mLo52, mLo52, 
/* '\uE0xx' */ mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, 
/* '\uF0xx' */ mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo1, mLo52, mLo52, mLo1, mLo1, mLo1, mLo1, mLo1};

#endregion


    static sbyte Map(int code)
    { 
        if (code <= 65535)
            return map[code / 256][code % 256];
        else
            return (sbyte)68;
    }

    static Table[] NxS = new Table[210] {
/* NxS[   0] */ new Table(0, 0, 0, null), // Shortest string ""
/* NxS[   1] */ // Shortest string "8"
      new Table(47, 59, -1, new short[] {166, -1, -1, -1, 166, 166, 
          166, -1, -1, -1, -1, 1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, 1, 166, -1, -1, -1, -1, -1, 1, 165, -1, 166, 77, 1, 166, 1, 
          -1, -1, 166, 77, -1, -1, 166, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, 166}),
/* NxS[   2] */ // Shortest string "a"
      new Table(44, 62, -1, new short[] {6, 6, -1, 2, 6, 6, 
          6, 2, 2, 2, 6, 6, 6, 6, 2, 2, 6, 6, 6, 6, -1, -1, 
          6, -1, -1, -1, 2, 2, 6, 6, 6, 6, -1, 2, -1, -1, 2, 47, 
          2, 2, 2, 6, -1, 2, 47, 6, 6, 2, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, 6, 6, 2}),
/* NxS[   3] */ // Shortest string "h"
      new Table(44, 62, -1, new short[] {6, 6, -1, 6, 6, 6, 
          6, 6, 81, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, 
          6, -1, -1, -1, 6, 6, 6, 6, 6, 6, -1, 6, -1, -1, 6, 6, 
          6, 6, 6, 6, -1, 6, 6, 6, 6, 6, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, 6, 6, 6}),
/* NxS[   4] */ // Shortest string "1"
      new Table(47, 59, -1, new short[] {166, -1, -1, -1, 166, 166, 
          166, -1, -1, -1, -1, 1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, 1, 166, -1, -1, -1, -1, -1, 1, 165, -1, 166, 77, 4, 78, 4, 
          -1, -1, 166, 77, -1, -1, 166, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, 166}),
/* NxS[   5] */ // Shortest string "0"
      new Table(47, 59, -1, new short[] {166, -1, -1, -1, 166, 166, 
          166, -1, -1, -1, -1, 1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, 1, 166, -1, -1, -1, -1, -1, 1, 165, -1, 166, 77, 4, 78, 4, 
          167, -1, 166, 77, -1, -1, 166, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, 166}),
/* NxS[   6] */ // Shortest string "x"
      new Table(64, 59, 6, new short[] {-1, -1, 6, -1, -1, -1, 
          6, 6, 6, 6, 6, 6, -1, 6, -1, -1, 6, 6, 6, 6, 6, 6, 
          -1, 6, 6, 6, 6, 6, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, 6, 6, 6, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, 6, 6, -1}),
/* NxS[   7] */ // Shortest string "C"
      new Table(44, 62, -1, new short[] {6, 6, -1, 2, 6, 40, 
          6, 2, 2, 2, 6, 6, 6, 6, 2, 2, 6, 6, 6, 6, -1, -1, 
          6, -1, -1, -1, 2, 2, 40, 6, 6, 6, -1, 2, -1, -1, 2, 67, 
          2, 2, 2, 6, -1, 2, 67, 6, 6, 2, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, 6, 6, 2}),
/* NxS[   8] */ // Shortest string "F"
      new Table(44, 62, -1, new short[] {6, 6, -1, 2, 65, 6, 
          6, 2, 2, 2, 6, 6, 6, 6, 2, 2, 6, 6, 6, 40, -1, -1, 
          6, -1, -1, -1, 2, 2, 6, 6, 6, 6, -1, 2, -1, -1, 2, 47, 
          2, 2, 2, 6, -1, 2, 47, 6, 6, 2, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, 6, 65, 2}),
/* NxS[   9] */ // Shortest string "&"
      new Table(16, 1, -1, new short[] {64}),
/* NxS[  10] */ // Shortest string "%"
      new Table(18, 1, -1, new short[] {62}),
/* NxS[  11] */ // Shortest string "="
      new Table(19, 1, -1, new short[] {61}),
/* NxS[  12] */ // Shortest string "<"
      new Table(19, 3, -1, new short[] {58, 59, 60}),
/* NxS[  13] */ // Shortest string ">"
      new Table(19, 3, -1, new short[] {56, -1, 57}),
/* NxS[  14] */ // Shortest string "!"
      new Table(19, 1, -1, new short[] {55}),
/* NxS[  15] */ // Shortest string "+"
      new Table(19, 5, -1, new short[] {51, -1, -1, -1, 54}),
/* NxS[  16] */ // Shortest string "-"
      new Table(19, 6, -1, new short[] {51, -1, -1, -1, -1, 53}),
/* NxS[  17] */ // Shortest string "*"
      new Table(19, 1, -1, new short[] {51}),
/* NxS[  18] */ // Shortest string "/"
      new Table(19, 8, -1, new short[] {51, -1, -1, -1, -1, -1, 
          46, 52}),
/* NxS[  19] */ // Shortest string "M"
      new Table(44, 62, -1, new short[] {6, 6, -1, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 50, 6, 6, 6, -1, -1, 
          6, -1, -1, -1, 6, 6, 6, 6, 50, 6, -1, 6, -1, -1, 6, 6, 
          6, 6, 6, 6, -1, 6, 6, 6, 6, 6, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, 6, 6, 6}),
/* NxS[  20] */ // Shortest string "D"
      new Table(44, 62, -1, new short[] {6, 6, -1, 2, 6, 6, 
          6, 2, 48, 2, 6, 6, 6, 6, 2, 2, 6, 6, 6, 6, -1, -1, 
          6, -1, -1, -1, 2, 2, 6, 6, 6, 6, -1, 2, -1, -1, 2, 47, 
          2, 2, 2, 6, -1, 2, 47, 6, 6, 2, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, 6, 6, 2}),
/* NxS[  21] */ // Shortest string "("
      new Table(25, 1, -1, new short[] {46}),
/* NxS[  22] */ new Table(0, 0, -1, null), // Shortest string ")"
/* NxS[  23] */ new Table(0, 0, -1, null), // Shortest string "["
/* NxS[  24] */ new Table(0, 0, -1, null), // Shortest string "]"
/* NxS[  25] */ new Table(0, 0, -1, null), // Shortest string "{"
/* NxS[  26] */ new Table(0, 0, -1, null), // Shortest string "}"
/* NxS[  27] */ new Table(0, 0, -1, null), // Shortest string ","
/* NxS[  28] */ new Table(0, 0, -1, null), // Shortest string ":"
/* NxS[  29] */ new Table(0, 0, -1, null), // Shortest string "?"
/* NxS[  30] */ new Table(0, 0, -1, null), // Shortest string ";"
/* NxS[  31] */ // Shortest string "\t"
      new Table(46, 1, -1, new short[] {31}),
/* NxS[  32] */ // Shortest string "P"
      new Table(44, 62, -1, new short[] {6, 6, -1, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 40, 6, 6, 6, 6, 6, 6, 6, -1, -1, 
          6, -1, -1, -1, 6, 6, 6, 40, 6, 6, -1, 6, -1, -1, 6, 6, 
          6, 6, 6, 6, -1, 6, 6, 6, 6, 6, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, 6, 6, 6}),
/* NxS[  33] */ // Shortest string "s"
      new Table(44, 62, -1, new short[] {6, 6, -1, 6, 6, 6, 
          6, 6, 6, 6, 6, 42, 6, 6, 6, 6, 6, 6, 43, 6, -1, -1, 
          6, -1, -1, -1, 6, 6, 6, 6, 6, 43, -1, 6, -1, -1, 6, 6, 
          6, 6, 6, 6, -1, 6, 6, 6, 6, 6, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, 6, 6, 6}),
/* NxS[  34] */ // Shortest string "t"
      new Table(64, 59, 6, new short[] {-1, -1, 6, -1, -1, -1, 
          6, 39, 6, 6, 6, 6, -1, 6, -1, -1, 39, 6, 6, 6, 6, 6, 
          -1, 6, 6, 6, 6, 6, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, 6, 6, 6, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, 6, 6, -1}),
/* NxS[  35] */ // Shortest string "\r"
      new Table(65, 1, -1, new short[] {36}),
/* NxS[  36] */ new Table(0, 0, -1, null), // Shortest string "\n"
/* NxS[  37] */ new Table(0, 0, -1, null), // Shortest string "'"
/* NxS[  38] */ new Table(0, 0, -1, null), // Shortest string "\""
/* NxS[  39] */ // Shortest string "ta"
      new Table(64, 59, 6, new short[] {-1, -1, 6, -1, -1, -1, 
          6, 6, 6, 6, 6, 6, -1, 6, -1, -1, 6, 6, 6, 40, 6, 6, 
          -1, 6, 6, 6, 6, 6, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, 6, 6, 6, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, 6, 6, -1}),
/* NxS[  40] */ // Shortest string "Cr"
      new Table(64, 59, 6, new short[] {-1, -1, 6, -1, -1, -1, 
          6, 6, 6, 6, 6, 6, -1, 6, -1, 41, 6, 6, 6, 6, 6, 6, 
          -1, 6, 6, 6, 6, 6, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, 6, 6, 6, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, 6, 6, -1}),
/* NxS[  41] */ new Table(0, 0, -1, null), // Shortest string "Cr$"
/* NxS[  42] */ // Shortest string "sP"
      new Table(44, 62, -1, new short[] {6, 6, -1, 6, 6, 6, 
          6, 6, 6, 40, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, 
          6, -1, -1, -1, 6, 6, 6, 6, 6, 6, -1, 6, -1, -1, 6, 6, 
          6, 6, 6, 6, -1, 40, 6, 6, 6, 6, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, 6, 6, 6}),
/* NxS[  43] */ // Shortest string "st"
      new Table(44, 62, -1, new short[] {6, 6, -1, 6, 6, 40, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, 
          6, -1, -1, -1, 6, 6, 40, 6, 6, 6, -1, 6, -1, -1, 6, 6, 
          6, 6, 6, 6, -1, 6, 6, 6, 6, 6, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, 6, 6, 6}),
/* NxS[  44] */ new Table(0, 0, -1, null), // Shortest string "\xEF\xBD\xA2"
/* NxS[  45] */ new Table(0, 0, -1, null), // Shortest string "\xEF\xBD\xA3"
/* NxS[  46] */ new Table(0, 0, -1, null), // Shortest string "/*"
/* NxS[  47] */ // Shortest string "ah"
      new Table(64, 59, 6, new short[] {-1, -1, 6, -1, -1, -1, 
          6, 6, 6, 6, 6, 6, -1, 6, -1, -1, 6, 6, 6, 6, 6, 6, 
          -1, 6, 6, 6, 6, 6, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, 6, 6, 6, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, 6, 6, -1}),
/* NxS[  48] */ // Shortest string "DE"
      new Table(44, 62, -1, new short[] {6, 6, -1, 2, 6, 6, 
          6, 2, 2, 49, 6, 6, 6, 6, 2, 2, 6, 6, 6, 6, -1, -1, 
          6, -1, -1, -1, 2, 2, 6, 6, 6, 6, -1, 2, -1, -1, 2, 47, 
          2, 2, 2, 6, -1, 49, 47, 6, 6, 2, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, 6, 6, 2}),
/* NxS[  49] */ // Shortest string "DEC"
      new Table(44, 62, -1, new short[] {6, 6, -1, 2, 6, 6, 
          6, 2, 2, 2, 40, 6, 6, 6, 2, 2, 6, 6, 6, 6, -1, -1, 
          6, -1, -1, -1, 2, 2, 6, 6, 6, 6, -1, 2, -1, -1, 2, 47, 
          2, 2, 2, 6, -1, 2, 47, 6, 40, 2, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, 6, 6, 2}),
/* NxS[  50] */ // Shortest string "Ms"
      new Table(44, 62, -1, new short[] {6, 6, -1, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 40, 6, 6, 6, 40, 6, 6, -1, -1, 
          6, -1, -1, -1, 6, 6, 6, 6, 6, 6, -1, 6, -1, -1, 6, 6, 
          6, 6, 6, 40, -1, 6, 6, 6, 6, 6, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, 6, 6, 6}),
/* NxS[  51] */ new Table(0, 0, -1, null), // Shortest string "+="
/* NxS[  52] */ new Table(0, 0, -1, null), // Shortest string "//"
/* NxS[  53] */ new Table(0, 0, -1, null), // Shortest string "--"
/* NxS[  54] */ new Table(0, 0, -1, null), // Shortest string "++"
/* NxS[  55] */ new Table(0, 0, -1, null), // Shortest string "!="
/* NxS[  56] */ new Table(0, 0, -1, null), // Shortest string ">="
/* NxS[  57] */ new Table(0, 0, -1, null), // Shortest string ">>"
/* NxS[  58] */ new Table(0, 0, -1, null), // Shortest string "<="
/* NxS[  59] */ new Table(0, 0, -1, null), // Shortest string "<<"
/* NxS[  60] */ new Table(0, 0, -1, null), // Shortest string "<>"
/* NxS[  61] */ new Table(0, 0, -1, null), // Shortest string "=="
/* NxS[  62] */ new Table(0, 0, -1, null), // Shortest string "%%"
/* NxS[  63] */ new Table(0, 0, -1, null), // Shortest string "||"
/* NxS[  64] */ new Table(0, 0, -1, null), // Shortest string "&&"
/* NxS[  65] */ // Shortest string "FO"
      new Table(44, 62, -1, new short[] {6, 6, -1, 6, 6, 66, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, 
          6, -1, -1, -1, 6, 6, 66, 6, 6, 6, -1, 6, -1, -1, 6, 6, 
          6, 6, 6, 6, -1, 6, 6, 6, 6, 6, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, 6, 6, 6}),
/* NxS[  66] */ // Shortest string "FOr"
      new Table(44, 62, -1, new short[] {6, 6, -1, 6, 6, 6, 
          40, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, 
          6, -1, -1, -1, 6, 6, 6, 6, 6, 6, -1, 6, -1, -1, 6, 6, 
          6, 6, 6, 6, -1, 6, 6, 6, 6, 6, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, 40, 6, 6}),
/* NxS[  67] */ // Shortest string "Ch"
      new Table(44, 62, -1, new short[] {6, 6, -1, 6, 6, 40, 
          6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, -1, -1, 
          6, -1, -1, -1, 6, 6, 40, 6, 6, 6, -1, 6, -1, -1, 6, 6, 
          6, 6, 6, 6, -1, 6, 6, 6, 6, 6, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, 6, 6, 6}),
/* NxS[  68] */ new Table(0, 0, -1, null), // Shortest string "#ELsE"
/* NxS[  69] */ // Shortest string "#EnD"
      new Table(54, 37, -1, new short[] {147, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 147}),
/* NxS[  70] */ new Table(0, 0, -1, null), // Shortest string "#EnDIF"
/* NxS[  71] */ new Table(0, 0, -1, null), // Shortest string "#MODULE"
/* NxS[  72] */ new Table(0, 0, -1, null), // Shortest string "^#InCLUDE"
/* NxS[  73] */ // Shortest string "#IF\t"
      new Table(64, 2, 73, new short[] {-1, -1}),
/* NxS[  74] */ new Table(0, 0, -1, null), // Shortest string "#CCHK#IF"
/* NxS[  75] */ // Shortest string "#asM\r"
      new Table(65, 1, -1, new short[] {76}),
/* NxS[  76] */ new Table(0, 0, -1, null), // Shortest string "#asM\n"
/* NxS[  77] */ new Table(0, 0, -1, null), // Shortest string "8h"
/* NxS[  78] */ // Shortest string "1B"
      new Table(47, 59, -1, new short[] {166, -1, -1, -1, 166, 166, 
          166, -1, -1, -1, -1, 166, 166, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, 166, 166, -1, -1, -1, -1, -1, 166, -1, -1, 166, 77, 166, 166, 166, 
          -1, -1, 166, 77, -1, -1, 166, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, 166}),
/* NxS[  79] */ // Shortest string "$8"
      new Table(47, 59, -1, new short[] {79, -1, -1, -1, 79, 79, 
          79, -1, -1, -1, -1, 79, 79, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, 79, 79, -1, -1, -1, -1, -1, 79, -1, -1, 79, -1, 79, 79, 79, 
          -1, -1, 79, -1, -1, -1, 79, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, 79}),
/* NxS[  80] */ // Shortest string "8.8"
      new Table(58, 27, -1, new short[] {80, 80, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, 80, -1, -1, -1, -1, -1, -1, 80, -1, -1, 
          -1, -1, 80, -1, 80}),
/* NxS[  81] */ // Shortest string "hE"
      new Table(44, 62, -1, new short[] {6, 6, -1, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 82, 6, 6, 6, 6, 6, 6, -1, -1, 
          6, -1, -1, -1, 6, 6, 6, 6, 6, 6, -1, 6, -1, -1, 6, 6, 
          6, 6, 6, 82, -1, 6, 6, 6, 6, 6, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, 6, 6, 6}),
/* NxS[  82] */ // Shortest string "hEx"
      new Table(44, 62, -1, new short[] {6, 6, -1, 6, 6, 6, 
          6, 6, 6, 6, 6, 6, 6, 6, 40, 40, 6, 6, 6, 6, -1, -1, 
          6, -1, -1, -1, 6, 6, 6, 6, 6, 6, -1, 6, -1, -1, 6, 6, 
          6, 6, 6, 6, -1, 6, 6, 6, 6, 6, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, 6, 6, 6}),
/* NxS[  83] */ new Table(0, 0, -1, null), // Shortest string ".MOD."
/* NxS[  84] */ new Table(0, 0, -1, null), // Shortest string "./."
/* NxS[  85] */ new Table(0, 0, -1, null), // Shortest string ".*."
/* NxS[  86] */ new Table(0, 0, -1, null), // Shortest string ".>."
/* NxS[  87] */ new Table(0, 0, -1, null), // Shortest string ".>>."
/* NxS[  88] */ new Table(0, 0, -1, null), // Shortest string ".>=."
/* NxS[  89] */ new Table(0, 0, -1, null), // Shortest string ".<."
/* NxS[  90] */ new Table(0, 0, -1, null), // Shortest string ".<<."
/* NxS[  91] */ new Table(0, 0, -1, null), // Shortest string ".<=."
/* NxS[  92] */ new Table(0, 0, -1, null), // Shortest string "8"
/* NxS[  93] */ // Shortest string "*"
      new Table(26, 6, -1, new short[] {95, -1, -1, -1, -1, 95}),
/* NxS[  94] */ new Table(0, 0, -1, null), // Shortest string "\n"
/* NxS[  95] */ new Table(0, 0, -1, null), // Shortest string "*/"
/* NxS[  96] */ new Table(0, 0, -1, null), // Shortest string "8"
/* NxS[  97] */ new Table(0, 0, -1, null), // Shortest string "\n"
/* NxS[  98] */ new Table(0, 0, -1, null), // Shortest string "8"
/* NxS[  99] */ // Shortest string "<"
      new Table(11, 1, -1, new short[] {185}),
/* NxS[ 100] */ new Table(0, 0, -1, null), // Shortest string "\n"
/* NxS[ 101] */ new Table(0, 0, -1, null), // Shortest string "\""
/* NxS[ 102] */ new Table(0, 0, -1, null), // Shortest string ""
/* NxS[ 103] */ // Shortest string ""
      new Table(58, 27, -1, new short[] {108, 108, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, 108, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, 108, -1, 108}),
/* NxS[ 104] */ // Shortest string ""
      new Table(47, 59, -1, new short[] {106, -1, -1, -1, 106, 106, 
          106, -1, -1, -1, -1, 106, 106, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, 106, 106, -1, -1, -1, -1, -1, 106, -1, -1, 106, -1, 106, 106, 106, 
          -1, -1, 106, -1, -1, -1, 106, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, 106}),
/* NxS[ 105] */ new Table(0, 0, -1, null), // Shortest string ""
/* NxS[ 106] */ // Shortest string ""
      new Table(47, 59, -1, new short[] {107, -1, -1, -1, 107, 107, 
          107, -1, -1, -1, -1, 107, 107, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, 107, 107, -1, -1, -1, -1, -1, 107, -1, -1, 107, -1, 107, 107, 107, 
          -1, -1, 107, -1, -1, -1, 107, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, 107}),
/* NxS[ 107] */ new Table(0, 0, -1, null), // Shortest string ""
/* NxS[ 108] */ // Shortest string ""
      new Table(58, 27, -1, new short[] {109, 109, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, 109, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, 109, -1, 109}),
/* NxS[ 109] */ new Table(0, 0, -1, null), // Shortest string ""
/* NxS[ 110] */ new Table(0, 0, -1, null), // Shortest string "8"
/* NxS[ 111] */ new Table(0, 0, -1, null), // Shortest string "\n"
/* NxS[ 112] */ new Table(0, 0, -1, null), // Shortest string "'"
/* NxS[ 113] */ // Shortest string "8"
      new Table(64, 2, 113, new short[] {-1, -1}),
/* NxS[ 114] */ new Table(0, 0, -1, null), // Shortest string "\t"
/* NxS[ 115] */ // Shortest string "\r"
      new Table(64, 2, 113, new short[] {-1, 117}),
/* NxS[ 116] */ // Shortest string "\n"
      new Table(64, 2, 113, new short[] {-1, -1}),
/* NxS[ 117] */ new Table(0, 0, -1, null), // Shortest string "\r\n"
/* NxS[ 118] */ new Table(0, 0, -1, null), // Shortest string "8"
/* NxS[ 119] */ // Shortest string "#"
      new Table(52, 39, -1, new short[] {200, -1, 199, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          199}),
/* NxS[ 120] */ new Table(0, 0, -1, null), // Shortest string "\n"
/* NxS[ 121] */ new Table(0, 0, -1, null), // Shortest string "#ELsE"
/* NxS[ 122] */ // Shortest string "#EnD"
      new Table(54, 37, -1, new short[] {204, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 204}),
/* NxS[ 123] */ new Table(0, 0, -1, null), // Shortest string "#EnDIF"
/* NxS[ 124] */ new Table(0, 0, -1, null), // Shortest string "#IF"
/* NxS[ 125] */ new Table(0, 0, -1, null), // Shortest string "8"
/* NxS[ 126] */ new Table(0, 0, -1, null), // Shortest string "\n"
/* NxS[ 127] */ new Table(0, 0, -1, null), // Shortest string "8"
/* NxS[ 128] */ // Shortest string "#"
      new Table(52, 1, -1, new short[] {207}),
/* NxS[ 129] */ new Table(0, 0, -1, null), // Shortest string "\n"
/* NxS[ 130] */ // Shortest string "#EnD"
      new Table(54, 37, -1, new short[] {209, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 209}),
/* NxS[ 131] */ new Table(0, 0, -1, null), // Shortest string "#EnDIF"
/* NxS[ 132] */ // Shortest string ""
      new Table(40, 73, -1, new short[] {27, 28, 29, 30, 6, 6, 
          31, 8, 6, 6, 19, 20, 2, 7, 6, 32, 6, 6, 1, 1, 33, 6, 
          34, 6, 35, 36, 6, 37, -1, 38, 1, 2, 6, 6, 33, 34, -1, 1, 
          134, 167, 2, 3, 4, 2, 5, 6, 179, 7, 3, 6, 6, 8, 9, 136, 
          10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 6, 20, 21, 22, 23, 24, 
          25, 26, 137}),
/* NxS[ 133] */ // Shortest string "^"
      new Table(40, 73, -1, new short[] {27, 28, 29, 30, 6, 6, 
          31, 8, 6, 6, 19, 20, 2, 7, 6, 32, 6, 6, 1, 1, 33, 6, 
          34, 6, 35, 36, 6, 37, -1, 38, 1, 2, 6, 6, 33, 34, -1, 1, 
          134, 167, 2, 3, 4, 2, 5, 6, 135, 7, 3, 6, 6, 8, 9, 136, 
          10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 6, 20, 21, 22, 23, 24, 
          25, 26, 137}),
/* NxS[ 134] */ // Shortest string "."
      new Table(20, 8, -1, new short[] {168, 169, -1, -1, -1, 170, 
          171, 172}),
/* NxS[ 135] */ // Shortest string "^#"
      new Table(50, 54, -1, new short[] {142, -1, 143, -1, 141, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 139, 
          -1, -1, -1, -1, -1, -1, -1, -1, 139, -1, -1, -1, -1, -1, -1, 140, 
          -1, -1, 141, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 142}),
/* NxS[ 136] */ // Shortest string "|"
      new Table(17, 1, -1, new short[] {63}),
/* NxS[ 137] */ // Shortest string "\xEF"
      new Table(37, 1, -1, new short[] {138}),
/* NxS[ 138] */ // Shortest string "\xEF\xBD"
      new Table(38, 2, -1, new short[] {44, 45}),
/* NxS[ 139] */ // Shortest string "#a"
      new Table(60, 15, -1, new short[] {163, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, 163}),
/* NxS[ 140] */ // Shortest string "#C"
      new Table(11, 1, -1, new short[] {158}),
/* NxS[ 141] */ // Shortest string "^#I"
      new Table(47, 45, -1, new short[] {152, -1, -1, -1, -1, -1, 
          -1, -1, -1, 153, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, 153, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, 152}),
/* NxS[ 142] */ // Shortest string "#M"
      new Table(28, 21, -1, new short[] {148, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 148}),
/* NxS[ 143] */ // Shortest string "#E"
      new Table(56, 18, -1, new short[] {144, -1, -1, -1, -1, -1, 
          -1, 145, -1, -1, -1, -1, -1, -1, -1, -1, -1, 144}),
/* NxS[ 144] */ // Shortest string "#En"
      new Table(29, 23, -1, new short[] {69, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          69}),
/* NxS[ 145] */ // Shortest string "#EL"
      new Table(60, 15, -1, new short[] {146, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, 146}),
/* NxS[ 146] */ // Shortest string "#ELs"
      new Table(52, 1, -1, new short[] {68}),
/* NxS[ 147] */ // Shortest string "#EnDI"
      new Table(15, 33, -1, new short[] {70, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 70}),
/* NxS[ 148] */ // Shortest string "#MO"
      new Table(29, 23, -1, new short[] {149, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          149}),
/* NxS[ 149] */ // Shortest string "#MOD"
      new Table(66, 1, -1, new short[] {150}),
/* NxS[ 150] */ // Shortest string "#MODU"
      new Table(63, 1, -1, new short[] {151}),
/* NxS[ 151] */ // Shortest string "#MODUL"
      new Table(52, 1, -1, new short[] {71}),
/* NxS[ 152] */ // Shortest string "#IF"
      new Table(46, 1, -1, new short[] {73}),
/* NxS[ 153] */ // Shortest string "^#In"
      new Table(53, 35, -1, new short[] {154, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 154}),
/* NxS[ 154] */ // Shortest string "^#InC"
      new Table(63, 1, -1, new short[] {155}),
/* NxS[ 155] */ // Shortest string "^#InCL"
      new Table(66, 1, -1, new short[] {156}),
/* NxS[ 156] */ // Shortest string "^#InCLU"
      new Table(29, 23, -1, new short[] {157, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          157}),
/* NxS[ 157] */ // Shortest string "^#InCLUD"
      new Table(52, 1, -1, new short[] {72}),
/* NxS[ 158] */ // Shortest string "#CC"
      new Table(12, 1, -1, new short[] {159}),
/* NxS[ 159] */ // Shortest string "#CCH"
      new Table(13, 1, -1, new short[] {160}),
/* NxS[ 160] */ // Shortest string "#CCHK"
      new Table(10, 1, -1, new short[] {161}),
/* NxS[ 161] */ // Shortest string "#CCHK#"
      new Table(14, 1, -1, new short[] {162}),
/* NxS[ 162] */ // Shortest string "#CCHK#I"
      new Table(15, 1, -1, new short[] {74}),
/* NxS[ 163] */ // Shortest string "#as"
      new Table(27, 24, -1, new short[] {164, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, 164}),
/* NxS[ 164] */ // Shortest string "#asM"
      new Table(46, 20, -1, new short[] {164, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 75, 76}),
/* NxS[ 165] */ // Shortest string "8."
      new Table(58, 27, -1, new short[] {80, 80, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, 80, -1, -1, -1, -1, -1, -1, 80, -1, -1, 
          -1, -1, 80, -1, 80}),
/* NxS[ 166] */ // Shortest string "8a"
      new Table(47, 59, -1, new short[] {166, -1, -1, -1, 166, 166, 
          166, -1, -1, -1, -1, 166, 166, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, 166, 166, -1, -1, -1, -1, -1, 166, -1, -1, 166, 77, 166, 166, 166, 
          -1, -1, 166, 77, -1, -1, 166, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, 166}),
/* NxS[ 167] */ // Shortest string "$"
      new Table(47, 59, -1, new short[] {79, -1, -1, -1, 79, 79, 
          79, -1, -1, -1, -1, 79, 79, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, 79, 79, -1, -1, -1, -1, -1, 79, -1, -1, 79, -1, 79, 79, 79, 
          -1, -1, 79, -1, -1, -1, 79, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, 79}),
/* NxS[ 168] */ // Shortest string ".<"
      new Table(2, 19, -1, new short[] {89, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 177, 178}),
/* NxS[ 169] */ // Shortest string ".>"
      new Table(2, 20, -1, new short[] {86, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 175, -1, 176}),
/* NxS[ 170] */ // Shortest string ".*"
      new Table(2, 1, -1, new short[] {85}),
/* NxS[ 171] */ // Shortest string "./"
      new Table(2, 1, -1, new short[] {84}),
/* NxS[ 172] */ // Shortest string ".M"
      new Table(28, 1, -1, new short[] {173}),
/* NxS[ 173] */ // Shortest string ".MO"
      new Table(29, 1, -1, new short[] {174}),
/* NxS[ 174] */ // Shortest string ".MOD"
      new Table(2, 1, -1, new short[] {83}),
/* NxS[ 175] */ // Shortest string ".>="
      new Table(2, 1, -1, new short[] {88}),
/* NxS[ 176] */ // Shortest string ".>>"
      new Table(2, 1, -1, new short[] {87}),
/* NxS[ 177] */ // Shortest string ".<="
      new Table(2, 1, -1, new short[] {91}),
/* NxS[ 178] */ // Shortest string ".<<"
      new Table(2, 1, -1, new short[] {90}),
/* NxS[ 179] */ // Shortest string "#"
      new Table(50, 54, -1, new short[] {142, -1, 143, -1, 180, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 139, 
          -1, -1, -1, -1, -1, -1, -1, -1, 139, -1, -1, -1, -1, -1, -1, 140, 
          -1, -1, 180, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 142}),
/* NxS[ 180] */ // Shortest string "#I"
      new Table(15, 33, -1, new short[] {152, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 152}),
/* NxS[ 181] */ // Shortest string ""
      new Table(65, 37, 92, new short[] {94, 92, 92, 92, 92, 92, 
          92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 
          92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 93}),
/* NxS[ 182] */ // Shortest string ""
      new Table(65, 1, 96, new short[] {97}),
/* NxS[ 183] */ // Shortest string ""
      new Table(65, 32, 98, new short[] {100, 98, 98, 98, 101, 98, 
          98, 98, 98, 98, 98, 184, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 
          98, 98, 98, 98, 98, 98, 98, 98, 98, 99}),
/* NxS[ 184] */ // Shortest string ""
      new Table(57, 29, 102, new short[] {104, 103, 103, 102, 102, 102, 
          102, 102, 105, 102, 102, 102, 102, 103, 102, 102, 102, 102, 102, 102, 102, 102, 
          102, 102, 102, 103, 102, 103, 104}),
/* NxS[ 185] */ // Shortest string "<C"
      new Table(12, 1, -1, new short[] {186}),
/* NxS[ 186] */ // Shortest string "<CH"
      new Table(71, 1, -1, new short[] {187}),
/* NxS[ 187] */ // Shortest string "<CHA"
      new Table(72, 1, -1, new short[] {188}),
/* NxS[ 188] */ // Shortest string "<CHAR"
      new Table(11, 1, -1, new short[] {189}),
/* NxS[ 189] */ // Shortest string "<CHARC"
      new Table(28, 1, -1, new short[] {190}),
/* NxS[ 190] */ // Shortest string "<CHARCO"
      new Table(73, 1, -1, new short[] {191}),
/* NxS[ 191] */ // Shortest string "<CHARCON"
      new Table(74, 1, -1, new short[] {192}),
/* NxS[ 192] */ // Shortest string "<CHARCONS"
      new Table(75, 1, -1, new short[] {193}),
/* NxS[ 193] */ // Shortest string "<CHARCONST"
      new Table(21, 1, -1, new short[] {194}),
/* NxS[ 194] */ // Shortest string "<CHARCONST>"
      new Table(0, 1, -1, new short[] {195}),
/* NxS[ 195] */ // Shortest string ""
      new Table(65, 1, 102, new short[] {-1}),
/* NxS[ 196] */ // Shortest string ""
      new Table(65, 12, 110, new short[] {111, 110, 112, 110, 110, 110, 
          110, 110, 110, 110, 110, -1}),
/* NxS[ 197] */ // Shortest string ""
      new Table(46, 20, 113, new short[] {114, 113, 113, 113, 113, 113, 
          113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 115, 116}),
/* NxS[ 198] */ // Shortest string ""
      new Table(65, 22, 118, new short[] {120, 118, 118, 118, 118, 118, 
          118, 118, 118, 118, 118, 118, 118, 118, 118, 118, 118, 118, 118, 118, 118, 119}),
/* NxS[ 199] */ // Shortest string "#I"
      new Table(15, 33, -1, new short[] {124, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 124}),
/* NxS[ 200] */ // Shortest string "#E"
      new Table(56, 18, -1, new short[] {201, -1, -1, -1, -1, -1, 
          -1, 202, -1, -1, -1, -1, -1, -1, -1, -1, -1, 201}),
/* NxS[ 201] */ // Shortest string "#En"
      new Table(29, 23, -1, new short[] {122, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          122}),
/* NxS[ 202] */ // Shortest string "#EL"
      new Table(60, 15, -1, new short[] {203, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, 203}),
/* NxS[ 203] */ // Shortest string "#ELs"
      new Table(52, 1, -1, new short[] {121}),
/* NxS[ 204] */ // Shortest string "#EnDI"
      new Table(15, 33, -1, new short[] {123, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 123}),
/* NxS[ 205] */ // Shortest string ""
      new Table(65, 1, 125, new short[] {126}),
/* NxS[ 206] */ // Shortest string ""
      new Table(65, 22, 127, new short[] {129, 127, 127, 127, 127, 127, 
          127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 128}),
/* NxS[ 207] */ // Shortest string "#E"
      new Table(56, 18, -1, new short[] {208, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 208}),
/* NxS[ 208] */ // Shortest string "#En"
      new Table(29, 23, -1, new short[] {130, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          130}),
/* NxS[ 209] */ // Shortest string "#EnDI"
      new Table(15, 33, -1, new short[] {131, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 131}),
    };

int NextState() {
    if (code == ScanBuff.EndOfFile)
        return eofNum;
    else
        unchecked {
            int rslt;
            int idx = Map(code) - NxS[state].min;
            if (idx < 0) idx += 76;
            if ((uint)idx >= (uint)NxS[state].rng) rslt = NxS[state].dflt;
            else rslt = NxS[state].nxt[idx];
            return rslt;
        }
}

#endregion


#if BACKUP
        // ==============================================================
        // == Nested struct used for backup in automata that do backup ==
        // ==============================================================

        struct Context // class used for automaton backup.
        {
            public int bPos;
            public int rPos; // scanner.readPos saved value
            public int cCol;
            public int lNum; // Need this in case of backup over EOL.
            public int state;
            public int cChr;
        }
        
        private Context ctx = new Context();
#endif // BACKUP

        // ==============================================================
        // ==== Nested struct to support input switching in scanners ====
        // ==============================================================

		struct BufferContext {
            internal ScanBuff buffSv;
			internal int chrSv;
			internal int cColSv;
			internal int lNumSv;
		}

        // ==============================================================
        // ===== Private methods to save and restore buffer contexts ====
        // ==============================================================

        /// <summary>
        /// This method creates a buffer context record from
        /// the current buffer object, together with some
        /// scanner state values. 
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        BufferContext MkBuffCtx()
		{
			BufferContext rslt;
			rslt.buffSv = this.buffer;
			rslt.chrSv = this.code;
			rslt.cColSv = this.cCol;
			rslt.lNumSv = this.lNum;
			return rslt;
		}

        /// <summary>
        /// This method restores the buffer value and allied
        /// scanner state from the given context record value.
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void RestoreBuffCtx(BufferContext value)
		{
			this.buffer = value.buffSv;
			this.code = value.chrSv;
			this.cCol = value.cColSv;
			this.lNum = value.lNumSv;
        } 
        // =================== End Nested classes =======================

#if !NOFILES
     internal SLANGScanner(Stream file) {
            SetSource(file, 65001); // unicode option
        }

        public SLANGScanner(Stream file, string codepage) {
            SetSource(file, CodePageHandling.GetCodePage(codepage));
        }   
#endif // !NOFILES

     internal SLANGScanner() { }

        private int readPos;

        void GetCode()
        {
            if (code == '\n')  // This needs to be fixed for other conventions
                               // i.e. [\r\n\205\u2028\u2029]
            { 
                cCol = -1;
                lNum++;
            }
            readPos = buffer.Pos;

            // Now read new codepoint.
            code = buffer.Read();
            if (code > ScanBuff.EndOfFile)
            {
#if (!BYTEMODE)
                if (code >= 0xD800 && code <= 0xDBFF)
                {
                    int next = buffer.Read();
                    if (next < 0xDC00 || next > 0xDFFF)
                        code = ScanBuff.UnicodeReplacementChar;
                    else
                        code = (0x10000 + ((code & 0x3FF) << 10) + (next & 0x3FF));
                }
#endif
                cCol++;
            }
        }

        void MarkToken()
        {
#if (!PERSIST)
            buffer.Mark();
#endif
            tokPos = readPos;
            tokLin = lNum;
            tokCol = cCol;
        }
        
        void MarkEnd()
        {
            tokTxt = null;
            tokEPos = readPos;
            tokELin = lNum;
            tokECol = cCol;
        }

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int Peek()
        {
            int rslt, codeSv = code, cColSv = cCol, lNumSv = lNum, bPosSv = buffer.Pos;
            GetCode(); rslt = code;
            lNum = lNumSv; cCol = cColSv; code = codeSv; buffer.Pos = bPosSv;
            return rslt;
        }

        // ==============================================================
        // =====    Initialization of string-based input buffers     ====
        // ==============================================================

        /// <summary>
        /// Create and initialize a StringBuff buffer object for this scanner
        /// </summary>
        /// <param name="source">the input string</param>
        /// <param name="offset">starting offset in the string</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(string source, int offset)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.buffer.Pos = offset;
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }

        // ================ LineBuffer Initialization ===================
        /// <summary>
        /// Create and initialize a LineBuff buffer object for this scanner
        /// </summary>
        /// <param name="source">the list of input strings</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(IList<string> source)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            this.lNum = 0;
            GetCode();
        }

#if !NOFILES        
        // =============== StreamBuffer Initialization ==================

        /// <summary>
        /// Create and initialize a StreamBuff buffer object for this scanner.
        /// StreamBuff is buffer for 8-bit byte files.
        /// </summary>
        /// <param name="source">the input byte stream</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(Stream source)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }
        
#if !BYTEMODE
        // ================ TextBuffer Initialization ===================

        /// <summary>
        /// Create and initialize a TextBuff buffer object for this scanner.
        /// TextBuff is a buffer for encoded unicode files.
        /// </summary>
        /// <param name="source">the input text file</param>
        /// <param name="fallbackCodePage">Code page to use if file has
        /// no BOM. For 0, use machine default; for -1, 8-bit binary</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(Stream source, int fallbackCodePage)
        {
            this.buffer = ScanBuff.GetBuffer(source, fallbackCodePage);
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }
#endif // !BYTEMODE
#endif // !NOFILES
        
        // ==============================================================

#if BABEL
        //
        //  Get the next token for Visual Studio
        //
        //  "state" is the inout mode variable that maintains scanner
        //  state between calls, using the EolState property. In principle,
        //  if the calls of EolState are costly set could be called once
        //  only per line, at the start; and get called only at the end
        //  of the line. This needs more infrastructure ...
        //
        public int GetNext(ref int state, out int start, out int end)
        {
                Token next;
            int s, e;
            s = state;        // state at start
            EolState = state;
                next = (Token)Scan();
            state = EolState;
            e = state;       // state at end;
            start = tokPos;
            end = tokEPos - 1; // end is the index of last char.
            return (int)next;
        }        
#endif // BABEL

        // ======== AbstractScanner<> Implementation =========

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yylex")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yylex")]
        public override int yylex()
        {
            // parserMax is set by reflecting on the Tokens
            // enumeration.  If maxParseToken is defined
            // that is used, otherwise int.MaxValue is used.
            int next;
            do { next = Scan(); } while (next >= parserMax);
            return next;
        }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yypos { get { return tokPos; } }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yyline { get { return tokLin; } }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yycol { get { return tokCol; } }

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yytext")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yytext")]
        public string yytext
        {
            get 
            {
                if (tokTxt == null) 
                    tokTxt = buffer.GetString(tokPos, tokEPos);
                return tokTxt;
            }
        }

        /// <summary>
        /// Discards all but the first "n" codepoints in the recognized pattern.
        /// Resets the buffer position so that only n codepoints have been consumed;
        /// yytext is also re-evaluated. 
        /// </summary>
        /// <param name="n">The number of codepoints to consume</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void yyless(int n)
        {
            buffer.Pos = tokPos;
            // Must read at least one char, so set before start.
            cCol = tokCol - 1; 
            GetCode();
            // Now ensure that line counting is correct.
            lNum = tokLin;
            // And count the rest of the text.
            for (int i = 0; i < n; i++) GetCode();
            MarkEnd();
        }
       
        //
        //  It would be nice to count backward in the text
        //  but it does not seem possible to re-establish
        //  the correct column counts except by going forward.
        //
        /// <summary>
        /// Removes the last "n" code points from the pattern.
        /// </summary>
        /// <param name="n">The number to remove</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void _yytrunc(int n) { yyless(yyleng - n); }
        
        //
        // This is painful, but we no longer count
        // codepoints.  For the overwhelming majority 
        // of cases the single line code is fast, for
        // the others, well, at least it is all in the
        // buffer so no files are touched. Note that we
        // can't use (tokEPos - tokPos) because of the
        // possibility of surrogate pairs in the token.
        //
        /// <summary>
        /// The length of the pattern in codepoints (not the same as 
        /// string-length if the pattern contains any surrogate pairs).
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yyleng")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yyleng")]
        public int yyleng
        {
            get {
                if (tokELin == tokLin)
                    return tokECol - tokCol;
                else
#if BYTEMODE
                    return tokEPos - tokPos;
#else
                {
                    int ch;
                    int count = 0;
                    int save = buffer.Pos;
                    buffer.Pos = tokPos;
                    do {
                        ch = buffer.Read();
                        if (!char.IsHighSurrogate((char)ch)) count++;
                    } while (buffer.Pos < tokEPos && ch != ScanBuff.EndOfFile);
                    buffer.Pos = save;
                    return count;
                }
#endif // BYTEMODE
            }
        }
        
        // ============ methods available in actions ==============

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal int YY_START {
            get { return currentScOrd; }
            set { currentScOrd = value; 
                  currentStart = startState[value]; 
            } 
        }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void BEGIN(int next) {
            currentScOrd = next;
            currentStart = startState[next];
        }

        // ============== The main tokenizer code =================

        int Scan() {
                for (; ; ) {
                    int next;              // next state to enter
#if LEFTANCHORS
                    for (;;) {
                        // Discard characters that do not start any pattern.
                        // Must check the left anchor condition after *every* GetCode!
                        state = ((cCol == 0) ? anchorState[currentScOrd] : currentStart);
                        if ((next = NextState()) != goStart) break; // LOOP EXIT HERE...
                        GetCode();
                    }
                    
#else // !LEFTANCHORS
                    state = currentStart;
                    while ((next = NextState()) == goStart) {
                        // At this point, the current character has no
                        // transition from the current state.  We discard 
                        // the "no-match" char.   In traditional LEX such 
                        // characters are echoed to the console.
                        GetCode();
                    }
#endif // LEFTANCHORS                    
                    // At last, a valid transition ...    
                    MarkToken();
                    state = next;
                    GetCode();                    
#if BACKUP
                    bool contextSaved = false;
                    while ((next = NextState()) > eofNum) { // Exit for goStart AND for eofNum
                        if (state <= maxAccept && next > maxAccept) { // need to prepare backup data
                            // Store data for the *latest* accept state that was found.
                            SaveStateAndPos( ref ctx );
                            contextSaved = true;
                        }
                        state = next;
                        GetCode();
                    }
                    if (state > maxAccept && contextSaved)
                        RestoreStateAndPos( ref ctx );
#else  // BACKUP
                    while ((next = NextState()) > eofNum) { // Exit for goStart AND for eofNum
                         state = next;
                         GetCode();
                    }
#endif // BACKUP
                    if (state <= maxAccept) {
                        MarkEnd();
#region ActionSwitch
#pragma warning disable 162, 1522
    switch (state)
    {
        case eofNum:
            switch (currentStart) {
                case 181:
yyerror("EOF in comment");
                    break;
                case 183:
yyerror("EOF in string");       
                        lexStrBuffer.Clear();
                        BEGIN(INITIAL);
                    break;
                case 196:
yyerror("EOF in string");       
                        lexStrBuffer.Clear();
                        BEGIN(INITIAL);
                    break;
                case 206:
yyerror("EOF in #ASM");
                    break;
            }
            if (yywrap())
                return (int)Token.EOF;
            break;
        case 1: // Recognized '{Number}',	Shortest string "8"
        case 4: // Recognized '{Number}',	Shortest string "1"
        case 5: // Recognized '{Number}',	Shortest string "0"
        case 47: // Recognized '{Number}',	Shortest string "ah"
        case 67: // Recognized '{Number}',	Shortest string "Ch"
        case 77: // Recognized '{Number}',	Shortest string "8h"
        case 78: // Recognized '{Number}',	Shortest string "1B"
        case 79: // Recognized '{Number}',	Shortest string "$8"
        case 80: // Recognized '{Number}',	Shortest string "8.8"
GetNumber(); return (int)Token.CONSTANT;
            break;
        case 2: // Recognized '{Identifier}',	Shortest string "a"
        case 3: // Recognized '{Identifier}',	Shortest string "h"
        case 6: // Recognized '{Identifier}',	Shortest string "x"
        case 7: // Recognized '{Identifier}',	Shortest string "C"
        case 8: // Recognized '{Identifier}',	Shortest string "F"
        case 19: // Recognized '{Identifier}',	Shortest string "M"
        case 20: // Recognized '{Identifier}',	Shortest string "D"
        case 32: // Recognized '{Identifier}',	Shortest string "P"
        case 33: // Recognized '{Identifier}',	Shortest string "s"
        case 34: // Recognized '{Identifier}',	Shortest string "t"
        case 39: // Recognized '{Identifier}',	Shortest string "ta"
        case 40: // Recognized '{Identifier}',	Shortest string "Cr"
        case 42: // Recognized '{Identifier}',	Shortest string "sP"
        case 43: // Recognized '{Identifier}',	Shortest string "st"
        case 48: // Recognized '{Identifier}',	Shortest string "DE"
        case 49: // Recognized '{Identifier}',	Shortest string "DEC"
        case 50: // Recognized '{Identifier}',	Shortest string "Ms"
        case 65: // Recognized '{Identifier}',	Shortest string "FO"
        case 66: // Recognized '{Identifier}',	Shortest string "FOr"
        case 81: // Recognized '{Identifier}',	Shortest string "hE"
        case 82: // Recognized '{Identifier}',	Shortest string "hEx"
nextBraceIsArray = true; return (int)GetIdentifier();
            break;
        case 9: // Recognized '\&',	Shortest string "&"
return (int)Token.OP_AMP;
            break;
        case 10: // Recognized '{PER}',	Shortest string "%"
return (int)Token.PER;
            break;
        case 11: // Recognized '{OP_EQ}',	Shortest string "="
nextBraceIsArray = false; return (int)Token.OP_EQ;
            break;
        case 12: // Recognized '\<',	Shortest string "<"
return (int)GetCompop();
            break;
        case 13: // Recognized '\>',	Shortest string ">"
return (int)GetCompop();
            break;
        case 14: // Recognized '{EXC}',	Shortest string "!"
yylval.symbol = "!"; return (int)Token.EXC;
            break;
        case 15: // Recognized '{OP_ADD}',	Shortest string "+"
return (int)GetAddop();
            break;
        case 16: // Recognized '{OP_SUB}',	Shortest string "-"
return (int)GetAddop();
            break;
        case 17: // Recognized '{OP_MUL}',	Shortest string "*"
return (int)Token.OP_MUL;
            break;
        case 18: // Recognized '{OP_DIV}',	Shortest string "/"
return (int)Token.OP_DIV;
            break;
        case 21: // Recognized '{P_OPEN}',	Shortest string "("
return (int)Token.P_OPEN;
            break;
        case 22: // Recognized '{P_CLOSE}',	Shortest string ")"
nextBraceIsArray = false; return (int)Token.P_CLOSE;
            break;
        case 23: // Recognized '{B_OPEN}',	Shortest string "["
int result;
                    result = nextBraceIsArray ? (int)Token.AB_OPEN : (int)Token.B_OPEN;
                    nextBraceIsArray = false;
                    return result;
            break;
        case 24: // Recognized '{B_CLOSE}',	Shortest string "]"
nextBraceIsArray = true; return (int)Token.B_CLOSE;
            break;
        case 25: // Recognized '{BR_OPEN}',	Shortest string "{"
return (int)Token.BR_OPEN;
            break;
        case 26: // Recognized '{BR_CLOSE}',	Shortest string "}"
return (int)Token.BR_CLOSE;
            break;
        case 27: // Recognized '{COMMA}',	Shortest string ","
return (int)Token.COMMA;
            break;
        case 28: // Recognized '{COLON}',	Shortest string ":"
nextBraceIsArray = false; return (int)Token.COLON;
            break;
        case 29: // Recognized '{QUESTION}',	Shortest string "?"
return (int)Token.QUESTION;
            break;
        case 30: // Recognized '{SC}',	Shortest string ";"
nextBraceIsArray = false; return (int)Token.SC;
            break;
        case 31: // Recognized '{Space}+',	Shortest string "\t"
nextBraceIsArray = false;
            break;
        case 35: // Recognized '{Eol}',	Shortest string "\r"
        case 36: // Recognized '{Eol}',	Shortest string "\n"
LocationNextLine(); nextBraceIsArray = false;
                genSourceComment(buffer.GetString(prevTokEPos,tokEPos));
                prevTokEPos = tokEPos;
            break;
        case 37: // Recognized '"\'"',	Shortest string "'"
lexStrBuffer = new StringBuilder();
                        BEGIN(CHARCONST);
            break;
        case 38: // Recognized '"\""',	Shortest string "\""
lexStrBuffer = new StringBuilder();
                        BEGIN(STRING);
            break;
        case 41: // Recognized '{STRFUNC}',	Shortest string "Cr$"
yylval.symbol = yytext; return (int)Token.STRFUNC;
            break;
        case 44: // Recognized '{F_OPEN}',	Shortest string "\xEF\xBD\xA2"
return (int)Token.F_OPEN;
            break;
        case 45: // Recognized '{F_CLOSE}',	Shortest string "\xEF\xBD\xA3"
return (int)Token.F_CLOSE;
            break;
        case 46: // Recognized '{CMTSTART}',	Shortest string "/*"
BEGIN(COMMENT);
            break;
        case 51: // Recognized '"+="|"-="|"*="|"/="',	Shortest string "+="
yylval.op = yytext; return (int)Token.assignop;
            break;
        case 52: // Recognized '"//"',	Shortest string "//"
BEGIN(LINECOMMENT);
            break;
        case 53: // Recognized '"--"',	Shortest string "--"
return (int)GetIncDecOp();
            break;
        case 54: // Recognized '"++"',	Shortest string "++"
return (int)GetIncDecOp();
            break;
        case 55: // Recognized '"!="',	Shortest string "!="
return (int)GetEqop();
            break;
        case 56: // Recognized '\>\=',	Shortest string ">="
return (int)GetCompop();
            break;
        case 57: // Recognized '{OP_RSHIFT}',	Shortest string ">>"
return (int)GetShiftop();
            break;
        case 58: // Recognized '\<\=',	Shortest string "<="
return (int)GetCompop();
            break;
        case 59: // Recognized '{OP_LSHIFT}',	Shortest string "<<"
return (int)GetShiftop();
            break;
        case 60: // Recognized '{CP_NE}',	Shortest string "<>"
return (int)GetEqop();
            break;
        case 61: // Recognized '{CP_EQ}',	Shortest string "=="
return (int)GetEqop();
            break;
        case 62: // Recognized '{FLOAT}',	Shortest string "%%"
return (int)Token.FLOAT;
            break;
        case 63: // Recognized '\|\|',	Shortest string "||"
return (int)Token.logor;
            break;
        case 64: // Recognized '\&\&',	Shortest string "&&"
return (int)Token.logand;
            break;
        case 68: // Recognized '{PREELSE}',	Shortest string "#ELsE"
BEGIN(PREIFSKIP);
            break;
        case 69: // Recognized '{PREEND}',	Shortest string "#EnD"
        case 70: // Recognized '{PREEND}',	Shortest string "#EnDIF"
BEGIN(SKIPEOL);
            break;
        case 71: // Recognized '{MODULE}',	Shortest string "#MODULE"
moduleCount++;
    moduleMode = true;
    // BEGIN(INITIAL);
    // yylval.str = yytext;
    return (int)Token.MODULE;
            break;
        case 72: // Recognized '^#[Ii][Nn][Cc][Ll][Uu][Dd][Ee]',	Shortest string "^#InCLUDE"
BEGIN(INCL);
            break;
        case 73: // Recognized '{PREIF}[ \t]+{dotchr}*',	Shortest string "#IF\t"
if(preIfSkipCount != 0)
    {
        // æ¥ãªãã¯ã
        preIfSkipCount++;
    } else {
        if(CheckConst(yytext)){
            BEGIN(INITIAL);
        } else {
            BEGIN(PREIFSKIP);
        };
    }
            break;
        case 74: // Recognized '"#CCHK#IF"',	Shortest string "#CCHK#IF"
return (int)Token.PRECONST;
            break;
        case 75: // Recognized '{ASM}{Space}*{Eol}',	Shortest string "#asM\r"
        case 76: // Recognized '{ASM}{Space}*{Eol}',	Shortest string "#asM\n"
lexStrBuffer = new StringBuilder();
                      BEGIN(ASM);
            break;
        case 83: // Recognized '".MOD."',	Shortest string ".MOD."
return (int)Token.OP_SMOD;
            break;
        case 84: // Recognized '"./."',	Shortest string "./."
return (int)Token.OP_SDIV;
            break;
        case 85: // Recognized '".*."',	Shortest string ".*."
return (int)Token.OP_SMUL;
            break;
        case 86: // Recognized '".>."',	Shortest string ".>."
return (int)GetScompop();
            break;
        case 87: // Recognized '".>>."',	Shortest string ".>>."
return (int)GetSshiftop();
            break;
        case 88: // Recognized '".>=."',	Shortest string ".>=."
return (int)GetScompop();
            break;
        case 89: // Recognized '".<."',	Shortest string ".<."
return (int)GetScompop();
            break;
        case 90: // Recognized '".<<."',	Shortest string ".<<."
return (int)GetSshiftop();
            break;
        case 91: // Recognized '".<=."',	Shortest string ".<=."
return (int)GetScompop();
            break;
        case 92: // In <COMMENT> Recognized '[^\n]',	Shortest string "8"
        case 93: // In <COMMENT> Recognized '[^\n]',	Shortest string "*"
{}
            break;
        case 94: // In <COMMENT> Recognized '\n',	Shortest string "\n"
LocationNextLine();
            break;
        case 95: // In <COMMENT> Recognized '{CMTEND}',	Shortest string "*/"
BEGIN(INITIAL);

/* Line Comment */
            break;
        case 96: // In <LINECOMMENT> Recognized '[^\n]',	Shortest string "8"
{}
            break;
        case 97: // In <LINECOMMENT> Recognized '\n',	Shortest string "\n"
BEGIN(INITIAL); LocationNextLine();
            break;
        case 98: // In <STRING> Recognized '[^\\\n"]',	Shortest string "8"
        case 99: // In <STRING> Recognized '[^\\\n"]',	Shortest string "<"
lexStrBuffer.Append(yytext);
            break;
        case 100: // In <STRING> Recognized '\n',	Shortest string "\n"
yyerror("Unterminated string");       
                        lexStrBuffer.Clear();
                        BEGIN(INITIAL);
                        LocationNextLine();
            break;
        case 101: // In <STRING> Recognized '"\""',	Shortest string "\""
BEGIN(INITIAL);
                        yylval.str = lexStrBuffer.ToString();
                        return (int)Token.STRING;
            break;
        case 102: // In <STRING> Recognized '\\[^\n]|<CHARCONST>\\[^\n]',	Shortest string ""
        case 104: // In <STRING> Recognized '\\[^\n]|<CHARCONST>\\[^\n]',	Shortest string ""
switch(yytext[yyleng-1]){
                    case 'n' :
                    case '/' : lexStrBuffer.Append((char)0x0d);
                                // TODO LSX-Dodgersã§ã¯ãããæå¹ã«ããªãã¨é§ç®
                               //lexStrBuffer.Append((char)0x0a);
                               break;

                    case 'C' :
                    case 'c' : lexStrBuffer.Append((char)0x0c);  
                               break;

                    case 'R' :
                    case 'r' :
                               lexStrBuffer.Append((char)0x1c);
                               //lexStrBuffer.Append('\r');
                               break;

                    case 'L' :
                    case 'l' : lexStrBuffer.Append((char)0x1d);
                               break;

                    case 'U' :
                    case 'u' : lexStrBuffer.Append((char)0x1e);
                               break;

                    case 'D' :
                    case 'd' : lexStrBuffer.Append((char)0x1f);
                               break;
                    default  : 
                        lexStrBuffer.Append('\\');
                        lexStrBuffer.Append(yytext[yyleng-1]);
                    break;
                    }
            break;
        case 103: // In <STRING> Recognized '\\{oct}',	Shortest string ""
        case 108: // In <STRING> Recognized '\\{oct}',	Shortest string ""
        case 109: // In <STRING> Recognized '\\{oct}',	Shortest string ""
{
                        int value = Convert.ToInt32(yytext.Substring(2), 8);
                        lexStrBuffer.Append((char)value);
                        }
            break;
        case 105: // In <STRING> Recognized '\\\n',	Shortest string ""
{}
            break;
        case 106: // In <STRING> Recognized '\\{hex}',	Shortest string ""
        case 107: // In <STRING> Recognized '\\{hex}',	Shortest string ""
{
                        int value = Convert.ToInt32(yytext.Substring(2), 16);
                        lexStrBuffer.Append((char)value);
                        }
            break;
        case 110: // In <CHARCONST> Recognized '[^\\\n']',	Shortest string "8"
lexStrBuffer.Append(yytext);
            break;
        case 111: // In <CHARCONST> Recognized '\n',	Shortest string "\n"
yyerror("Unterminated char");       
                        lexStrBuffer.Clear();
                        BEGIN(INITIAL);
                        LocationNextLine();
            break;
        case 112: // In <CHARCONST> Recognized '"\'"',	Shortest string "'"
BEGIN(INITIAL);
                        GetChar(lexStrBuffer.ToString());
                        return (int)Token.CONSTANT;
            break;
        case 113: // In <INCL> Recognized '[^ \t]{dotchr}*',	Shortest string "8"
BEGIN(INITIAL); TryInclude(yytext);
            break;
        case 114: // In <INCL> Recognized '[ \t]',	Shortest string "\t"
/* skip whitespace */
            break;
        case 115: // In <INCL> Recognized '{Eol}',	Shortest string "\r"
        case 116: // In <INCL> Recognized '{Eol}',	Shortest string "\n"
        case 117: // In <INCL> Recognized '{Eol}',	Shortest string "\r\n"
BEGIN(INITIAL); TryInclude(null);
            break;
        case 118: // In <PREIFSKIP> Recognized '[^\n]',	Shortest string "8"
        case 119: // In <PREIFSKIP> Recognized '[^\n]',	Shortest string "#"
{}
            break;
        case 120: // In <PREIFSKIP> Recognized '\n',	Shortest string "\n"
LocationNextLine();
            break;
        case 121: // In <PREIFSKIP> Recognized '{PREELSE}',	Shortest string "#ELsE"
BEGIN(SKIPEOL);
            break;
        case 122: // In <PREIFSKIP> Recognized '{PREEND}',	Shortest string "#EnD"
        case 123: // In <PREIFSKIP> Recognized '{PREEND}',	Shortest string "#EnDIF"
BEGIN(SKIPEOL);
            break;
        case 124: // In <PREIFSKIP> Recognized '{PREIF}',	Shortest string "#IF"
preIfSkipCount++;
            break;
        case 125: // In <SKIPEOL> Recognized '[^\n]',	Shortest string "8"
{}
            break;
        case 126: // In <SKIPEOL> Recognized '\n',	Shortest string "\n"
if(preIfSkipCount == 0)
    {
        BEGIN(INITIAL);
        if(moduleMode)
        {
            // end module
            moduleMode = false;
            return (int)Token.MODULEEND;
        }
    } else {
        BEGIN(PREIFSKIP);
        preIfSkipCount--;
    }
    LocationNextLine();
            break;
        case 127: // In <ASM> Recognized '[^\n]',	Shortest string "8"
        case 128: // In <ASM> Recognized '[^\n]',	Shortest string "#"
lexStrBuffer.Append(yytext);
            break;
        case 129: // In <ASM> Recognized '\n',	Shortest string "\n"
lexStrBuffer.Append("\n"); LocationNextLine();
            break;
        case 130: // In <ASM> Recognized '{PREEND}',	Shortest string "#EnD"
        case 131: // In <ASM> Recognized '{PREEND}',	Shortest string "#EnDIF"
BEGIN(INITIAL);
                        yylval.str = lexStrBuffer.ToString();
                        return (int)Token.PLAIN;
            break;
        default:
            break;
    }
#pragma warning restore 162, 1522
#endregion
                    }
                }
        }

#if BACKUP
        void SaveStateAndPos(ref Context ctx) {
            ctx.bPos  = buffer.Pos;
            ctx.rPos  = readPos;
            ctx.cCol  = cCol;
            ctx.lNum  = lNum;
            ctx.state = state;
            ctx.cChr  = code;
        }

        void RestoreStateAndPos(ref Context ctx) {
            buffer.Pos = ctx.bPos;
            readPos = ctx.rPos;
            cCol  = ctx.cCol;
            lNum  = ctx.lNum;
            state = ctx.state;
            code  = ctx.cChr;
        }
#endif  // BACKUP

        // ============= End of the tokenizer code ================

#if STACK        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void yy_clear_stack() { scStack.Clear(); }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal int yy_top_state() { return scStack.Peek(); }
        
        internal void yy_push_state(int state)
        {
            scStack.Push(currentScOrd);
            BEGIN(state);
        }
        
        internal void yy_pop_state()
        {
            // Protect against input errors that pop too far ...
            if (scStack.Count > 0) {
				int newSc = scStack.Pop();
				BEGIN(newSc);
            } // Otherwise leave stack unchanged.
        }
 #endif // STACK

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void ECHO() { Console.Out.Write(yytext); }
        
#region UserCodeSection

void LocationAddColumn(int cnt)
    {
        yylloc = new QUT.Gppg.LexLocation(yylloc.StartLine, yylloc.StartColumn, yylloc.EndLine, yylloc.EndColumn + cnt);
    }

    void LocationNextLine()
    {
        yylloc = new QUT.Gppg.LexLocation(yylloc.StartLine, yylloc.StartColumn, yylloc.EndLine + 1, 0);
    }

    void LocationNext()
    {
    yylloc = new QUT.Gppg.LexLocation(yylloc.EndLine, yylloc.EndColumn + 1, yylloc.EndLine, yylloc.EndColumn );
    }

    void PushLocation()
    {
    locationStack.Push(new LocationInfo(currentFileName, yylloc));
    }

    void LocationInit()
    {
        yylloc = new QUT.Gppg.LexLocation(0, 0, 0, 0);
    }

    void PopLocation()
    {
        var info = locationStack.Pop();
        currentFileName = info.FileName;
        yylloc = info.Location;
    }

    private void StartPreIf(string exprStr)
    {
        if (string.IsNullOrEmpty(exprStr))
        {
            Console.Error.WriteLine("#IF, no CONST");
        }
        else 
        {
            BufferContext savedCtx = MkBuffCtx();

            byte[] inputBuffer = System.Text.Encoding.UTF8.GetBytes(exprStr + ";");
            MemoryStream stream = new MemoryStream(inputBuffer);
            var charsetDetectedResult = UtfUnknown.CharsetDetector.DetectFromStream(stream);
            stream.Position = 0;
            SetSource(stream, CodePageHandling.GetCodePage(charsetDetectedResult.Detected.EncodingName));
            buffStack.Push(new ContextInfo(savedCtx, false));
        }
    }

    private void TryInclude(string fName)
    {
        if (string.IsNullOrEmpty(fName))
            Console.Error.WriteLine("#INCLUDE, no filename");
        else 
            try {
                if(fName[0] == '"')
                {
                  fName = fName.Trim('"');
                }
                BufferContext savedCtx = MkBuffCtx();

                var filePath = SLANGCommonUtility.GetSourcePath(fName);
                var stream = new FileStream(filePath, FileMode.Open);
                var charsetDetectedResult = UtfUnknown.CharsetDetector.DetectFromStream(stream);
                stream.Position = 0;
                SetSource(stream, CodePageHandling.GetCodePage(charsetDetectedResult.Detected.EncodingName));
                Console.WriteLine("; include {0}", fName);
                buffStack.Push(new ContextInfo(savedCtx, true)); // Don't push until file open succeeds!
                PushLocation();
                LocationInit();
                currentFileName = fName;
            }
            catch(Exception e)
            {
                throw new FileNotFoundException("#include, could not open file \"" + fName + "\"");
            }
    }

    protected override bool yywrap()
    {
        if (buffStack.Count == 0) return true;
        var info = buffStack.Pop();
        RestoreBuffCtx(info.context);
        if(info.useLocation)
        {
          PopLocation();
        }
        return false;
    }

#endregion
    } // end class $Scanner


} // end namespace
