#!/usr/bin/env python3
"""banjo_extract_syms.py - banjo driver の .sym から、 曲 asm が参照する driver label を
WLA-DX の `.define` (EQU) として抽出する。

banjo の曲データ (json2sms 出力 asm) は driver の関数 label を絶対参照する
(`.dw banjo_init_opm` や multi-chip 時の `call banjo_update_channels_ay/opm` 等)。 曲を driver と
別ビルドするため、 driver build 後にその label の絶対アドレスを EQU 化して曲側に注入する。

アドレスについて:
  WLA-DX の .sym は label を **CPU 絶対アドレス**で出力する (driver build の memorymap SLOT 0 =
  BANJO_ORG がそのまま反映される。 例: BANJO_ORG=$8000 なら banjo_init_opm=$8956)。 よって本ツールは
  sym 値を一切加工せずそのまま .define する。 BANJO_ORG を変えて driver を再ビルドすれば sym も
  追従するので、 曲側の EQU も自動的に正しい絶対アドレスになる。

抽出ロジック (= 固定 allowlist でなく曲 asm の実参照から):
  1. song asm の各行からコメント (`;` 以降) を除去
  2. token `banjo_[A-Za-z0-9_]+` を全部抽出 (= 参照候補)
  3. song asm 内で**定義**されている同名 label は除外 (= 曲側 stub ラベル定義を EQU 化しない)
  4. driver .sym に存在するものだけ `.define <name> $<addr>` を出力 (sym 値そのまま)
  5. driver .sym に**無い** banjo_* 参照が残ったら **error 終了** (= 曲が壊れたまま進むのを防ぐ)

Usage:
  python3 banjo_extract_syms.py <driver.sym> <song.asm> -o banjo_syms.inc
"""

import argparse
import re
import sys


def parse_driver_sym(path):
    """driver .sym → {label: addr_int}。 WLA-DX sym 形式 `BB:AAAA name` (bank:addr、 CRLF 可)。
    末尾の `_sizeof_*` 等 (コロン無し 8 桁形式) は行フォーマットでマッチしないので自然に除外される。"""
    syms = {}
    with open(path, encoding="utf-8", errors="replace") as f:
        for ln in f:
            ln = ln.replace("\r", "").rstrip("\n")
            m = re.match(r"^[0-9a-fA-F]+:([0-9a-fA-F]{4})\s+(\S+)$", ln)
            if m:
                syms[m.group(2)] = int(m.group(1), 16)
    return syms


def scan_song(path):
    """song asm → (参照 banjo_* set, 定義 banjo_* set)。
    参照 = コメント除去後の token、 定義 = 行頭 `label:` 形式。"""
    refs = set()
    defs = set()
    with open(path, encoding="utf-8", errors="replace") as f:
        for ln in f:
            ln = ln.replace("\r", "").rstrip("\n")
            code = ln.split(";", 1)[0]   # コメント除去
            # 定義 label (行頭の `name:`)
            md = re.match(r"^\s*(banjo_[A-Za-z0-9_]+):", code)
            if md:
                defs.add(md.group(1))
            # 参照 token
            for tok in re.findall(r"banjo_[A-Za-z0-9_]+", code):
                refs.add(tok)
    return refs, defs


def main():
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("driver_sym", help="banjo driver の .sym")
    p.add_argument("song_asm", help="json2sms 出力の曲 .asm")
    p.add_argument("-o", "--output", required=True, help="出力 banjo_syms.inc (WLA .define)")
    args = p.parse_args()

    syms = parse_driver_sym(args.driver_sym)
    if not syms:
        print(f"banjo_extract_syms: no labels parsed from {args.driver_sym}", file=sys.stderr)
        return 1

    refs, defs = scan_song(args.song_asm)
    # 曲側で定義されている label は除外 (= driver から注入しない)
    needed = sorted(refs - defs)

    missing = [n for n in needed if n not in syms]
    if missing:
        print("banjo_extract_syms: ERROR - song references banjo_* labels not in driver.sym:",
              file=sys.stderr)
        for n in missing:
            print(f"  {n}", file=sys.stderr)
        print("  → driver build と曲の chip 構成が不一致の可能性 (= driver に該当 chip を含めるか確認)",
              file=sys.stderr)
        return 1

    # sym 値は既に CPU 絶対アドレスなのでそのまま .define する。
    resolved = [(n, syms[n]) for n in needed if n in syms]

    lines = [
        "; banjo_syms.inc - auto-generated by banjo_extract_syms.py (編集禁止)",
        f"; driver.sym = {args.driver_sym}  song = {args.song_asm}",
        f"; {len(resolved)} driver label(s) referenced by song, injected as WLA .define",
        "",
    ]
    for n, a in resolved:
        lines.append(f".define {n} ${a:04x}")

    with open(args.output, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"banjo_extract_syms: wrote {args.output} ({len(resolved)} symbols)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
