#!/usr/bin/env python3
"""banjo_prep_song.py - json2sms 出力の曲 asm を「単独ビルド可能」な wrapper に包む。

banjo の曲 asm は内部ポインタ (pattern/order/instrument の `.dw <song-local label>`) を **絶対
16bit アドレス**で焼き込むため、 曲を**実ロードアドレスでビルド**しないと内部ポインタが壊れる
(json2sms の出力自体には memorymap が無い)。 また曲は driver の関数 label を絶対参照するので
EQU 注入 (banjo_extract_syms.py が出す banjo_syms.inc) を取り込む必要がある。 本ツールは生成済み
曲 asm を include する WLA-DX 用 wrapper を生成し、 そのまま wla-z80 できる asm を出力する:

  1. memorymap を load-addr 起点で生成:
       SLOT 0     -> load-addr
       SLOTSIZE   -> $10000 - load-addr   (load-addr..$FFFF を丁度カバー、 64KB 超え防止)
       BANKSIZE   -> $10000 - load-addr
     (.ORG $0000 は据置 = memory は SLOT base + ORG = load-addr)
  2. banjo_syms.inc を include (= driver label の EQU 注入)
  3. .ORG $0000 直後に song asm を include

json2sms 自体は不改変 (clock 補正以外 diff を増やさない方針)。

Usage:
  python3 banjo_prep_song.py <song.asm> --load-addr 0xB000 \
      --syms-include banjo_syms.inc -o song_ready.asm
"""

import argparse
import os
import sys


def main():
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("song_asm", help="json2sms 出力の曲 .asm")
    p.add_argument("--load-addr", type=lambda x: int(x, 0), required=True,
                   help="曲 bin の実ロードアドレス (例 0xB000)")
    p.add_argument("--syms-include", required=True,
                   help="driver label の EQU を持つ include ファイル名 (banjo_extract_syms.py 出力)")
    p.add_argument("-o", "--output", required=True, help="出力先 (整形済み曲 asm)")
    args = p.parse_args()

    load = args.load_addr
    if not (0 < load < 0x10000):
        print(f"banjo_prep_song: ERROR - load-addr ${load:04x} は 0<addr<0x10000 の範囲外",
              file=sys.stderr)
        return 1
    span = 0x10000 - load

    if not os.path.exists(args.song_asm):
        print(f"banjo_prep_song: ERROR - song asm not found: {args.song_asm}", file=sys.stderr)
        return 1
    if not os.path.exists(args.syms_include):
        print(f"banjo_prep_song: ERROR - syms include not found: {args.syms_include}", file=sys.stderr)
        return 1

    out = [
        "; banjo song build wrapper - auto-generated by banjo_prep_song.py (編集禁止)",
        f"; song asm = {args.song_asm}",
        f"; syms inc = {args.syms_include}",
        f"; load     = ${load:04x}",
        "",
        ".MEMORYMAP",
        "DEFAULTSLOT 0",
        f"SLOTSIZE ${span:04x}",
        f"SLOT 0 ${load:04x}",
        ".ENDME",
        ".ROMBANKMAP",
        "BANKSTOTAL 1",
        f"BANKSIZE ${span:04x}",
        "BANKS 1",
        ".ENDRO",
        "",
        f'.include "{args.syms_include}"',
        "",
        ".BANK 0 SLOT 0",
        ".ORG $0000",
        f'.include "{args.song_asm}"',
        "",
        "; 確認用 marker。 trim_to_end は最大使用アドレス基準なので、この label 単独には依存しない。",
        '.SECTION "BANJO_SONG_END" FREE',
        "banjo_song_end:",
        ".ENDS",
    ]

    with open(args.output, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"banjo_prep_song: wrote {args.output} (load=${load:04x} span=${span:04x})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
